name: Backend Prod Deployment

on:
  push:
    branches: [main]
    paths:
      - "Backend/**"
  pull_request:
    branches: [main]
    paths:
      - "Backend/**"

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: Backend/package-lock.json

      - name: Install dependencies
        working-directory: ./Backend
        run: npm ci

  deploy-backend-prod:
    needs: build-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render (handled by Render's auto-deploy)
        run: echo "Deployment is handled by Render's auto-deploy feature. No action needed here."
