name: Frontend Production Deployment

on:
  push:
    branches: [main]
    paths:
      - "Frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "Frontend/**"

jobs:
  deploy-frontend-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to AWS Amplify (handled by Amplify Console)
        run: echo "Deployment is handled by AWS Amplify Console. No action needed here."
